---
title: "visualisation-for-ftt-power-paper"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r imports}
library(tidyverse)
library("viridis")
```

```{r}
both_capacity = read_csv("/Users/alexanderkell/Documents/PhD/Projects/17-ftt-power-reinforcement/notebooks/data/processed/both_capacity_long.csv")
head(both_capacity)
```

```{r}
both_capacity = both_capacity %>% group_by(variable) %>% mutate(average_contributed = sum(value_both))
both_capacity = rename(both_capacity, c("Technology" = "variable"))
```

```{r}

historical_data_points = 44
historical_years = 44/4-1

both_capacity$index = both_capacity$index - historical_years

electricity_generated_plot= ggplot(filter(both_capacity, average_contributed> 500000), aes(x=index, y=value_both, color=Technology)) + geom_line(size=1) + theme_classic() + theme(text = element_text(size=27)) + xlab("Year") + ylab("Electricity Produced by Technology (GWh)")  + geom_vline(aes(xintercept = 2017, linetype = 'RL Starts'), colour = 'black', size=1.5)+scale_linetype_manual(name = '',
                        values = c('RL Starts' = 1),
                        guide = guide_legend(override.aes = list(colour = 'black')))

print(electricity_generated_plot)

ggsave("figures/electricity_generated_plot.pdf", electricity_generated_plot, dpi=1000, width = 30, height = 20, units = "cm")

```


```{r}
carbon_emissions = read_csv("/Users/alexanderkell/Documents/PhD/Projects/17-ftt-power-reinforcement/data/outputs/carbon_emissions.csv")

uk_emissions = carbon_emissions[,0:24]
ireland_emissions = carbon_emissions[,25:48]

total_emissions = uk_emissions + ireland_emissions

emissions = data.frame(year = seq(2003,2050.5,0.25), emissions = rowSums(total_emissions))
```

```{r}
emissions_plot = ggplot(data = emissions, aes(x=year, y=emissions)) + geom_line() + theme_classic() + theme(text = element_text(size=27)) + xlab("Year") + ylab(expression(paste("Emissions of CO ",~_2~," during (Mt/y)")))



print(emissions_plot)

ggsave("figures/emissions_plot.pdf", emissions_plot, dpi=1000, width = 30, height = 20, units = "cm")


```

```{r}

demand = read_csv("/Users/alexanderkell/Documents/PhD/Projects/17-ftt-power-reinforcement/data/outputs/demand.csv")


demand_summed = data.frame(year = seq(2013.25,2050,0.25), demand = rowSums(demand))

demand_plot = ggplot(data=demand_summed, aes(x=year, y=demand)) + geom_line()+ylim(c(0,max(demand_summed$demand)))+ theme_classic() + theme(text = element_text(size=27)) + xlab("Year") + ylab("Total electricity demand (GWh)")


print(demand_plot)

ggsave("figures/demand_plot.pdf", demand_plot, dpi=1000, width = 30, height = 20, units = "cm")



```



```{r}
tuning_training = read_csv("/Users/alexanderkell/Documents/PhD/Projects/17-ftt-power-reinforcement/data/outputs/hyperparameter_tuning_training.csv")
tuning_training

tuning_training$`Hyperparameter set` = as.factor(tuning_training$`Hyperparameter set`)
```

```{r}

hyperparameter_plot = ggplot(data=filter(tuning_training, timesteps_total>20000), aes(color=`Hyperparameter set`, group=`Hyperparameter set`, x=timesteps_total)) + geom_line(aes(y=episode_reward_min))+ geom_line(aes(y=episode_reward_mean))+ geom_line(aes(y=episode_reward_max)) + ylab("Episode Reward\n(Min, Mean and Max)") + xlab("Number of timesteps")+ theme_classic() + theme(text = element_text(size=27))+
    theme(legend.position="bottom")+ scale_x_continuous(labels = function(x) format(x, scientific = TRUE))

print(hyperparameter_plot)

ggsave("figures/hyperparameter_training.pdf", hyperparameter_plot, dpi=1000, width = 35, height = 20, units = "cm")


```
  
  
  
```{R}
  
training_dat = read_csv('~/Documents/PhD/Projects/17-ftt-power-reinforcement/notebooks/data/processed/training_data_all.csv')  

training_dat$`Reward type` = training_dat$Type

tail(filter(training_dat, Type=="Mean"))
```
```{r}
training_dat_plot = ggplot() +  geom_line(data=filter(training_dat, Step>5000), aes(x=Step, y=Value, color=`Reward type`)) + geom_hline(aes(yintercept=-2.1721175, linetype = "Levelling off"), colour="black")+ theme_classic()+ theme(text = element_text(size=27)) + xlab("Number of steps") + ylab("Reward")+scale_linetype_manual(name = '',
                        values = c('Levelling off' = 1),
                        guide = guide_legend(override.aes = list(colour = 'black')))

print(training_dat_plot)

ggsave("figures/runtime_steps_plot.pdf", training_dat_plot, dpi=1000, width = 35, height = 20, units = "cm")



```



```{r}
tuning_params = read_csv("/Users/alexanderkell/Documents/PhD/Projects/17-ftt-power-reinforcement/data/outputs/hyperparameter_tuning_training_with_params.csv")
head(tuning_params)
tuning_params$`Hyperparameter\nset` = tuning_params$`Hyperparameter set`

```
```{r}
hyperparameter_plot_params = ggplot(data=filter(tuning_params, timesteps_total>20000), aes(color=`Hyperparameter\nset`, group=`Hyperparameter\nset`, x=timesteps_total)) + geom_line(aes(y=episode_reward_min))+ geom_line(aes(y=episode_reward_mean))+ geom_line(aes(y=episode_reward_max)) + ylab("Episode Reward\n(Min, Mean and Max)") + xlab("Number of timesteps")+ theme_classic() + theme(text = element_text(size=27))+ theme(legend.position="bottom")+ scale_x_continuous(labels = function(x) format(x, scientific = TRUE)) +guides(color=guide_legend(nrow=3,byrow=TRUE))

print(hyperparameter_plot_params)

ggsave("figures/hyperparameter_plot_params.pdf", hyperparameter_plot_params, dpi=1000, width = 35, height = 20, units = "cm")


```